### PR TITLE
Fix egrid data if name not in properties

### PR DESCRIPTION
**Pull request by jpfleischer**
When using the `get_egrid_region` function, we expect it to work across all years.

However, in earlier years such as 2021, `name` is not the field for UACE. It is `SUBRGN`.

https://raw.githubusercontent.com/JGreenlee/e-mission-common/refs/heads/master/src/emcommon/resources/egrid2021_subregions_5pct.json

This fix accounts for either scenario.

### CODE REVIEW

**Comment by JGreenlee** [comment]
@jpfleischer Thanks for finding & fixing this oversight on my part. Ideally, our unit tests would have found this, but the tests I wrote in `test_egrid.py` and `test_footprint_calculations.py` only perform lookups in 2022 and 2023 (which is bad!)

Do you think you could add one or more tests that use 2021 or earlier? If not, I will do it when I have time.

**Comment by jpfleischer** [comment]
@JGreenlee  writing the test is no problem, but do you think you could merge https://github.com/JGreenlee/e-mission-common/pull/9 first so I can have a sanity check, because the pytests on my computer have very slight differences

```
FAILED test/metrics/test_transit.py::TestTransit::test_all_modes_nationwide - AssertionError: 483.0381873453086 != 486.96 within 2 places (3.9218126546913936 difference)
FAILED test/metrics/test_transit.py::TestTransit::test_bus_chicago - AssertionError: 1039.1030050798952 != 1048.12 within 2 places (9.016994920104707 difference)
```

I just want to know that GitHub Actions is succeeding, so I know something is wrong with my end

**Comment by JGreenlee** [comment]
@jpfleischer I merged #9 after making some adjustments (feel free to view what I changed). The workflow is working and passing on `master`.

I believe it will run if you push a commit to this PR with new tests.

**Comment by jpfleischer** [comment]
I have now implemented a 2021 NYC ebike test. @JGreenlee

**Review by JGreenlee — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
